-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.monedas
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 ),
    codigo character varying(3) NOT NULL,
    nombre character varying(100) NOT NULL,
    simbolo character varying(10) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_monedas_codigo UNIQUE (codigo)
);

CREATE TABLE IF NOT EXISTS public.paises
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 ),
    nombre character varying(100) NOT NULL,
    codigo character varying(2) NOT NULL,
    moneda_id bigint NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_paises_codigo UNIQUE (codigo)
);

CREATE TABLE IF NOT EXISTS public.ciudades
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 ),
    pais_id bigint NOT NULL,
    nombre character varying(150) NOT NULL,
    latitud double precision,
    longitud double precision,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.historial
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 ),
    usuario_id bigint NOT NULL,
    ciudad_id bigint NOT NULL,
    presupuesto_cop numeric(15, 2) NOT NULL,
    clima character varying(255) NOT NULL,
    tasa numeric(18, 8) NOT NULL,
    valor_convertido numeric(15, 2) NOT NULL,
    fecha timestamp with time zone NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.usuarios
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 ),
    nombre character varying(100) NOT NULL,
    correo character varying(150) NOT NULL,
    password_hash character varying(255) NOT NULL,
    idioma character varying(5) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_usuarios_correo UNIQUE (correo)
);

ALTER TABLE IF EXISTS public.paises
    ADD FOREIGN KEY (moneda_id)
    REFERENCES public.monedas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
 


ALTER TABLE IF EXISTS public.ciudades
    ADD FOREIGN KEY (pais_id)
    REFERENCES public.paises (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
   


ALTER TABLE IF EXISTS public.historial
    ADD FOREIGN KEY (usuario_id)
    REFERENCES public.usuarios (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
    


ALTER TABLE IF EXISTS public.historial
    ADD FOREIGN KEY (ciudad_id)
    REFERENCES public.ciudades (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
    

END;