<?php

class CreatePaises
{
    public function up(PDO $pdo): void
    {
        $pdo->exec("
            CREATE TABLE IF NOT EXISTS paises (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nombre VARCHAR(100) NOT NULL,
                codigo VARCHAR(2) NOT NULL UNIQUE,
                moneda_id BIGINT NOT NULL,
                CONSTRAINT fk_paises_moneda
                    FOREIGN KEY (moneda_id)
                    REFERENCES monedas (id)
                    ON UPDATE NO ACTION
                    ON DELETE NO ACTION
            );
        ");
    }
}