<?php

class CreateCiudades
{
    public function up(PDO $pdo): void
    {
        $pdo->exec("
            CREATE TABLE IF NOT EXISTS ciudades (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                pais_id BIGINT NOT NULL,
                nombre VARCHAR(150) NOT NULL,
                latitud DOUBLE PRECISION,
                longitud DOUBLE PRECISION,
                CONSTRAINT fk_ciudades_pais
                    FOREIGN KEY (pais_id)
                    REFERENCES paises (id)
                    ON UPDATE NO ACTION
                    ON DELETE NO ACTION
            );
        ");
    }
}