<?php

class CreateHistorial
{
    public function up(PDO $pdo): void
    {
        $pdo->exec("
            CREATE TABLE IF NOT EXISTS historial (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                usuario_id BIGINT NOT NULL,
                ciudad_id BIGINT NOT NULL,
                presupuesto_cop NUMERIC(15, 2) NOT NULL,
                clima VARCHAR(255) NOT NULL,
                tasa NUMERIC(18, 8) NOT NULL,
                valor_convertido NUMERIC(15, 2) NOT NULL,
                fecha TIMESTAMPTZ NOT NULL,
                CONSTRAINT fk_historial_usuario
                    FOREIGN KEY (usuario_id)
                    REFERENCES usuarios (id)
                    ON UPDATE NO ACTION
                    ON DELETE NO ACTION,
                CONSTRAINT fk_historial_ciudad
                    FOREIGN KEY (ciudad_id)
                    REFERENCES ciudades (id)
                    ON UPDATE NO ACTION
                    ON DELETE NO ACTION
            );
        ");
    }
}